---
title: "Learning to be a knapper: Key issues in cultural transmission of lithic technologies"
author:
- Cheng Liu^[Department of Anthropology, Emory University, Atlanta, GA, USA; raylc1996@outlook.com]
- Dietrich Stout^[Department of Anthropology, Emory University, Atlanta, GA, USA;  dwstout@emory.edu]
abstract: "The reconstruction of hominins’ cognitive evolution has always been a crucial but challenging task. Researchers from various disciplines have tried to approach this issue, among which British archaeologist Steven Mithen’s cathedral model is regarded as one of the earliest and most creative attempts. In this model, he proposed that the Neanderthal’s mind is like a cathedral with disconnected chapels. Specifically, Neanderthals possessed advanced social, natural history, technical, and even linguistic intelligence modules, but the first three modules are isolated from each other, meaning they cannot effectively use the knowledge from one domain to address the issue of another domain. This article challenges his reconstruction of Neanderthals’ cognitive capacities by presenting multiple forms of archaeological evidence bearing on various kinds of cross-domain thinking that has arisen over the past two decades. \\par \\textbf{Keywords:} Cultural transmission, Social learning, Lithic technology, Archaeological evidence"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
header-includes:
   - \usepackage{textcomp}
linestretch: 1.5
link-citations: yes
linkcolor: blue
bibliography: Exported Items.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Cultural transmission refers to a process of information exchange through non-genetic mechanisms that cause the similarities of cultural traits such as ideas, behaviors and artifacts among individuals [after @eerkensCulturalTransmissionTheory2014; @eerkens2007]. Its pivotal role in the generation of variation in material cultures as well as human evolution has been rediscovered and thus received extensive research attention from archaeologists in the past decades, which has been driven by the developments of cultural evolutionary thinking to large extent [@boyd1985; @cavalli-sforza1981]. However, the mechanism of cultural transmission has been long acknowledged and operationalized, implicitly or explicitly, in the ever-changing paradigm shifts of archaeological research, ranging from the early debate between migrationism and diffusionism in cultural history to more recent evolutionary approaches [@tostevin2013]. It lies in the very nature of the basic units of archaeological taxonomy, be it culture, technocomplexes, industries, traditions or facies, at both micro and macro levels. At the micro-level, the transmitted or shared practices in material culture within certain individuals make it possible for some artifact assemblages to be identified as comparable units. At the macro-level, it is the mechanistic underpinning of cross-unit cultural dynamics from both spatial (isolation and interaction/contact) and temporal (continuity and discontinuity) perspectives. Moreover, the extensive literature revolving around artifact standardization and craft specialization [e.g., @clark1995; @costin1991; @roux2015] occurred in more recent human evolution can be interpreted as structural changes of transmission systems, i.e., certain types of knowledge requiring high-level physical dexterity or time-consuming training can only be acquired and inherited among a small group of people.

Evolutionarily speaking, the high-fidelity transmission of information is suggested to be the key driver of cumulative culture that is peculiar to humans as opposed to many other socially transmitted behavioral traditions observed in non-human primates, cetaceans, or birds [@lewis2012]. The cumulativeness of human culture, namely the increasing diversity and complexity of cultural traits, reaches a peak with the invention and spread of writing systems. It has also been argued by @henrich2015 that collective brains composed of connected and inheritable cultural systems are the greatest selective advantage compared with other physiological features like big brains that explain the success of us, Homo sapiens, and our ancestral hominins in competition with other species.

In light of its tremendous significance, developing a set of robust tool kits to identify the cultural transmission in archaeological records is a critical mission. Specifically, stone artifacts will be the focus of this article due to their antiqueness, durability, ubiquity, and abundancy. In many Paleolithic occupations, they are also the only evidence available as all other organic remains were decomposed. This review paper pretends to summarize and reflect on the identifications and evolutionary implications of cultural transmission in the context of lithic artifacts, where three issues will be addressed in particular: 1) the debate over the origin of cultural transmission derived from the inconsistent terminology across literatures; 2) the identification of cultural transmission at the intra-site level; and 3) the identification of cultural transmission at the intra-site level. In addition to these crucial questions, a brief overview of theories pertinent to cultural transmission will also be presented below.

## Theorizing cultural transmission: Evolutionary and non-evolutionary perspectives

The fast-growing body of literature on the inference of cultural transmission patterns from material remains has been substantially triggered by the borrowing of mathematics models in population genetics during the early 1980s. @cavalli-sforza1981, two harbingers of formal cultural transmission theory, first systematically revealed the comparability between genetic and cultural inheritance systems in their groundbreaking work, *Cultural Transmission and Evolution: A Quantitative Approach*, which was foreshadowed by a series of prescient essays [@cavalli-sforza1973; @cavalli-sforza1975; @feldman1975]. In this book, they noticed that unlike genes that can only be transmitted from biological parents to offspring, a process termed as vertical transmission, the information sources for cultural transmission can be more complex. Aside from his/her parents, an individual can learn social norms and subsistence technology from their peers (horizontal transmission) or other non-parental figures from earlier generations (oblique transmission). Their models comparing frequency changes of cultural traits under different transmission conditions suggested that vertical transmission is much more powerful than oblique/horizontal transmission in the fixation or equilibrium with very limited innovations. In addition to a detailed analysis of transmission mechanism, they have also introduced other evolutionary dynamics to construct an integrative interpretation system of cultural change encompassing: 1) natural selection in terms of Darwinian fitness or reproductive success; 2) cultural selection functioning as decisions by individuals; 3) mutation that can be either purposive (innovation) or random (copying error); and 4) cultural drift as sampling fluctuations. Cultural evolves within a population possessing various cultural traits (mutation and drift) that are heritable (transmission) under both cultural and natural selections.

Their original models were later modified and adopted in the ethnographic case study of Aka pygmies, where two non-vertical transmissions was combined under the category of horizontal and the mechanisms of one-to-many and many-to-one were introduced [@hewlett1986]. This updated model has generated some relatively clear expectations (Table 1) that can be translated into measurable traits in artifact assemblages and thus lied the theoretical foundation of several archaeological studies of cultural transmission [@riede2019].

+-----------------------------------------------------+---------------------------------------+-----------------------------+----------------------------------------+-----------------------------------------------+
|                                                     | **Vertical transmission**             | **Horizontal transmission** | **One to many**                        | **Many to one**                               |
+=====================================================+=======================================+=============================+========================================+===============================================+
| **Transmitter**                                     | \footnotesize Parent(s)               | \footnotesize Unrelated     | \footnotesize Teacher/leader/media     | \footnotesize Older members of social group   |
+-----------------------------------------------------+---------------------------------------+-----------------------------+----------------------------------------+-----------------------------------------------+
| **Transmittee**                                     | \footnotesize Child                   | \footnotesize Unrelated     | \footnotesize Pupils/citizens/audience | \footnotesize Younger members of social group |
+-----------------------------------------------------+---------------------------------------+-----------------------------+----------------------------------------+-----------------------------------------------+
| **Acceptance of innovation**                        | \footnotesize Intermediate difficulty | \footnotesize Easy          | \footnotesize Easy                     | \footnotesize Very difficult                  |
+-----------------------------------------------------+---------------------------------------+-----------------------------+----------------------------------------+-----------------------------------------------+
| **Variation between individuals within population** | \footnotesize High                    | \footnotesize Can be high   | \footnotesize Low                      | \footnotesize Lowest                          |
+-----------------------------------------------------+---------------------------------------+-----------------------------+----------------------------------------+-----------------------------------------------+
| **Variation between groups**                        | \footnotesize High                    | \footnotesize Can be high   | \footnotesize Can be high              | \footnotesize Smallest                        |
+-----------------------------------------------------+---------------------------------------+-----------------------------+----------------------------------------+-----------------------------------------------+
| **Cultural evolution**                              | \footnotesize Slow                    | \footnotesize Can be rapid  | \footnotesize Most rapid               | \footnotesize Most conservative               |
+-----------------------------------------------------+---------------------------------------+-----------------------------+----------------------------------------+-----------------------------------------------+

: Models of cultural transmission [@hewlett1986].

Another major milestone in theoretical advances is Boyd and Richerson's [-@boyd1985] *Culture and Evolutionary Processes* elucidating the Dual Inheritance Theory (DIT) or gene-culture coevolution theory outlined in an earlier paper [@richerson1978], which has subsequently become an inclusive umbrella-term covering many relevant topics. The basic idea of DIT is rather simple. That is to say, human evolution is shaped by both genetic and cultural inheritance systems that interact with each other. Key thoughts within this theoretical framework underscore the impact of cultural evolution on biological evolution, which was rarely touched in Cavalli-Sforza and Marcus's work. For instance, they argued that effective social learning can reduce the selection pressure on genetic traits underlying phenotype.

In terms of cultural transmission, the highlight of their work is the introduction of three types of transmission biases and guided variation. The first one is direct bias, a very common and essentially content-based decision-making strategy. It happened when individuals choose to adopt the cultural traits they think are most suitable for their needs. Second, frequency-dependent bias, where the most common form is conformist bias meaning a cultural trait exhibited by the majority of the population will be more likely to be adopted by individuals. Third, indirect bias occurs when a trait possessed by successful or prestigious individuals has a higher chance to be transmitted. At last, guided variation, now more frequently termed as individual learning, refer to a process that individual will modify an acquired cultural trait via trial and error experiments. It was suggested that social learning will be favored over individual learning under less stable conditions due to its low cost. Furthermore, they have also brought more spatial dimension and coined the terms symmetrical (as an equivalent of vertical and oblique modes) and asymmetrical (as an equivalent of horizontal mode) transmission across space. The operating forces of these two mechanisms are quite different in that the former one is characterized by demic diffusion through natal dispersal while the latter is not.

It is worth noting that these two seminal monographs and the research traditions they represent belong to a larger wave of biologists' attempts on building a unified theoretical framework of gene and cultural evolution since the 1970s, such as @wilson1975, @dawkins1976, @alexander1979, @pulliam1980, @lumsden1981, but the impacts of other evolutionary theorists on material cultural studies have been under cultural selection and reduced to minimum by now. In contrast, DIT has been thriving since the 1990s as reflected in rapidly increasing number of publications in both theoretical [see @creanza2017; @feldman1996; @henrich2003; @shennan2008] and empirical studies [@kohler2004; @neiman1995; @steele2010], producing a widely used analytical framework and terminological system for many archaeological studies presented in this review.

Among all these developments, Eerkens and Lipo [-@eerkens2005; -@eerkens2007]'s "Accumulated Copying Error" (ACE) model has been frequently discussed and applied in lithic studies [@kempe2012; @okumura2014; @schillinger2014; @liu2020]. This model suggests that tiny mistakes will be generated during the copying process either because of the imperceptible magnitude of the difference or the physical inability of perfect imitation even with correct perception. Through repeated cultural transmission processes, these copying errors will result in a noticeable difference between the original artifact and later replicas.

In another vein, cultural transmission is deeply embedded in the intellectual landscape of social theories, among which Bourdieu's [-@bourdieu1977] practice theory is exceptionally popular among archaeologists interested in apprenticeship. The central concept of practice theory is habitus, defined as "a subjective but not individual system of internalized structures, schemes of perception, conception, and action common to all members of the same group or class [@bourdieu1977: 86]." Habitus emphasizes the embodied knowledge, such as stone knapping or pottery making, acquired and reinforced through daily practice and how it is structured and restructuring the reproduction of social identities. It has been effectively incorporated into the tool kits of many archeologists facing with post-processual critiques in investigating the embodiment and socialization of technologies through practices and learning and the collective memory it shaped [@hodder2004; @pauketat2005; @peelo2011].

One more non-evolutionary approach worth mentioning here is Ingold's [-@ingold1993] theoretical construct of taskscape, "an array of related activities" carrying forward social life that is inextricably bound with the landscape. This notion has provided a fresh analytical perspective for an emerging body of archaeology research [@homsey-messer2015; @logan2014; @michelaki2015; @rajala2017]. More importantly, it has been adopted and modified by Tostevin [-@tostevin2007; -@tostevin2013; @premo2016] for identifying cultural transmission in lithic assemblages. Built upon Ingold's taskscape and Carr's [-@carr1995] middle-range theory of artifact design, he coined the term taskscape visibility to refer to "the relationship between where, when, and with whom a cultural trait, such as a flintknapping behavior, is performed and the possible cultural transmission modes available for promulgating the trait into the next generation [@tostevin2013: 85]". This concept is then combined with social intimacy to predict certain aspects of lithic technology, mainly blank production, can only be visible and thus learned within socially intimate people like those living in the same camp. On the contrary, tool kit morphology is visible to more socially distant people such as two hunter-gatherers shortly meeting each other when their foraging landscape is overlapping.

A considerable distinction between the evolutionary and non-evolutionary approaches is that the latter strand put a strong emphasis on historical contingency, which is definitely not something should be ignored [@walsh2019], but this intrinsic feature also makes it hard to generate clear predictions that can be tested directly against archaeological data with proper middle-range models (with the exception of Tostevin's taskscape visibility). This might explain the huge imbalance between these two stances in terms of research productivity and subsequent disproportion of relevant case studies presented here. However, they are not necessarily incompatible in many contexts as argued in @ingold2007 and advocating a position of theoretical pluralism is more helpful for a better understanding of cultural transmission dynamics than underscoring their disparities.

## Unsettled terminology and the origin of cultural transmission

## Identifying cultural transmission processes at the intra-site level

## Identifying cultural transmission processes at the inter-site level

## Future directions

## References
