---
title: "Inferring cultural reproduction from lithic data: A critical review "
author:
- Cheng Liu^[Department of Anthropology, Emory University, Atlanta, GA, USA; raylc1996@outlook.com]
- Dietrich Stout^[Department of Anthropology, Emory University, Atlanta, GA, USA;  dwstout@emory.edu]
abstract: "The cultural reproduction of lithic technology, long an implicit assumption of archaeological theories, has garnered increasing attention over the past decades. Major debates ranging from the origins of the human culture capacity to the interpretation of spatiotemporal patterning now make explicit reference to social learning mechanisms and cultural evolutionary dynamics. This burgeoning literature has produced important insights and methodological innovations. However, this rapid growth has sometimes also led to confusion and controversy due to an under-examination of methodological assumptions and/or inconsistent use of terminology. The time is thus ripe for an assessment of recent progress in the study of the cultural reproduction of lithic technology. Here we review three central research topics: 1) culture origins, and the identification and interpretation of patterning at 2) intra-site, and 3) inter-site levels. This is followed by further thoughts on how to proceed from the current state of debate with theoretical and methodological pluralism. \\par \\textbf{Keywords:} Cultural transmission, Social learning, Lithic technology, Archaeological evidence"

date: "`r Sys.Date()`"
fontsize: 11pt
output: bookdown::pdf_document2
header-includes:
   - \usepackage{textcomp}
   - \usepackage{utopia}
   - \usepackage{lineno}
   - \linenumbers
   - \usepackage{float}
   - \floatplacement{figure}{H}
   - \usepackage{caption}
   - \captionsetup[figure]{font=scriptsize}
   - \captionsetup[table]{font=scriptsize}
linestretch: 1.5
link-citations: yes
linkcolor: blue
bibliography: References.bib
csl: evolutionary-anthropology.csl
---

```{r setup, include=FALSE}
## csl: apa.csl
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

From its earliest origins, archaeology has been concerned with identifying, documenting, and understanding past human cultures and their patterns of change through space and time. However, there has been little enduring consensus of what "culture" actually is or the processes by which it changes. Indeed, the history of the discipline has been one of ever-changing paradigm shifts, ranging from the early debate between migrationism and diffusionism in cultural history to the functionalism of processual archaeology and on to more recent evolutionary approaches [@tostevin2012]. Despite this fundamental ambiguity, the culture concept continues to lie at the heart of basic units of archaeological taxonomy (e.g., cultures, techno-complexes, industries, traditions, facies, etc.) across micro and macro levels. At the micro-level, shared practices in material culture within a population make it possible for some artifact assemblages to be identified as comparable units. At the macro-level, such sharing is the mechanistic underpinning of cross-unit cultural dynamics from both spatial (isolation and interaction/contact) and temporal (continuity and discontinuity) perspectives.

Although it is unlikely that a lasting consensus on the nature and workings of human culture will be achieved any time soon, recent archaeological approaches have been heavily influenced by the development of cultural evolutionary theory [@boyd1985; @cavalli-sforza1981] and psychological approaches to social learning [@whiten1992; @tomasello1993]. These influences have been immensely productive, but the rapid expansion of contemporary evolutionary archaeology has not been without growing pains and points of theoretical, methodological, and terminological confusion. The time is thus ripe for systematic review and assessment of the state of the field. To this end, we provide a critical overview of evolutionary archaeology theory and review its application to three key research topics in lithic technology: 1) culture origins, and the identification and interpretation of patterning at 2) intra-site, and 3) inter-site levels.

## A brief history of cultural evolution

Contemporary evolutionary archaeology is largely an outgrowth of formal approaches to cultural evolution (hereafter "cultural evolutionary theory" or CET) developed in the 1980s through the application of mathematical models borrowed from population genetics. Cavalli-Sforza and Feldman [-@cavalli-sforza1981] first systematically advocated the comparability between genetic and cultural inheritance systems in their groundbreaking work, *Cultural Transmission and Evolution: A Quantitative Approach*. In this book, they argued that the transmission of cultural knowledge is analogous to genetic inheritance in that it involves copying (reproduction) with the potential for modification (mutation), thus leading to variation and the potential for both random (drift) and adaptive (selection) evolution. They also considered important disanalogies. This included the distinction between the Darwinian selection of organisms through differential survival and reproduction (fitness) and the cultural selection of traits through individual decisions with respect to some form of cultural fitness (glossed as "appeal," p. 19). However, the bulk of the book was devoted exploring the disanalogy between the (almost) exclusively vertical transmission of genetic material from parents to offspring and the rampant horizontal (peer-to-peer) and oblique (non-parental elder to juvenile) transmission additionally present in cultural evolution.

Cavalli-Sforza and Feldman's original models were later modified and adopted in the ethnographic case study of Aka pygmies, in which oblique transmission was subsumed under horizontal and two new channels of one-to-many and many-to-one were introduced [@hewlett1986]. This updated model generated clear expectations (Table. 1) that could be readily translated into measurable traits in artifact assemblages and thus served as the theoretical foundation for archaeological studies of cultural transmission [@riede2019].

Concepts of cultural fitness and adaptation were more fully explored by Robert Boyd and Peter Richerson in their landmark *Culture and Evolutionary Processes* [-@boyd1985]. In this book, Boyd and Richerson developed the Dual Inheritance Theory (DIT, now commonly known as gene-culture coevolution theory) as a framework for considering potential interactions between cultural and biological evolution. In DIT, culture change can happen in two ways. First, natural selection can act on culture bearing individuals, in which case it is generally expected to increase the frequency of adaptive culture traits. Second, cultural selection can occur on the traits themselves, in which case biologically non-adaptive or even maladaptive traits can be favored. Cultural selection occurs through the adoption choices of individuals, and biases affecting these choices (i.e., the "cultural fitness" of variants) need not align with biological fitness. Boyd and Richerson thus conceptualize cultural fitness in terms of psychological processes or dispositions they term "transmission biases" that affect the likelihood of individuals adopting particular cultural traits. These include "direct" biases due to inherent features (e.g., effectiveness, memorability) of the trait, "indirect" biases based on characteristics of the model demonstrating the trait (e.g., success, prestige), and frequency-dependent biases such as a preference to copy the most common trait (conformity). Importantly for archaeology, DIT also considered the spatial dimensions of transmission, coining the terms symmetrical (as an equivalent of vertical and oblique modes) and asymmetrical (as an equivalent of horizontal mode) transmission across space. The operating forces of these two mechanisms are quite different in that the former one is characterized by demic diffusion through natal dispersal while the latter is not.

DIT holds that cultural evolution need not increase biological fitness in all cases, but nevertheless posits that it frequently does. In fact, cultural evolution has been held up as the critical "secret" to the demographic expansion and adaptive potential of our species [@boyd2011; @henrich2015]. There has thus been substantial interest in modeling conditions under which various transmission biases (often now termed social learning strategies [@kendal2018]) would be expected to produce biological fitness enhancement. For example, Boyd and Richerson [-@boyd1985] showed that conformity and prestige biases can increase the probability of individuals selecting locally adaptive traits even in the absence of any direct evaluation of trait merits. Under appropriate conditions, natural selection would thus favor these transmission biases, leading them to become species-typical features of human psychology that help to ensure the adaptive nature of cultural evolution. However, these biases would still be insufficient to explain the production of locally adaptive variants to copy in the first place.

Boyd and Richerson address this with the concept of "guided variation," now more frequently termed individual learning. It is controversial to what extent individual learning relies on "blind" trial and error vs. directed experimentation based on some form of causal understanding [@mesoudi2021], but in any case it is expected to guide variation toward desired outcomes. If, in line with Human Behavioral Ecology theory [@winterhalder2000], it is further assumed that humans generally act as biological fitness maximizers then such learning will be biased toward the production of adaptive variants so long as individuals have the cognitive, perceptual, and experiential capacity to identify the associated fitness benefits [@stout2021]. However, it is not clear that individual-learning objectives are necessarily any more likely to be related to biological fitness than are social-learning adoption choices and the concept of fitness as applied to cultural evolution remains under-theorized [@mesoudi2018].

The quantitative evolutionary approach pioneered by researchers like Cavalli-Sforza, Feldman, Boyd, and Richerson has been immensely influential and productive for the study of human culture and cognition in general [@henrich2015; @heyes2018; @laland2017] and for archaeological approaches to understanding past culture change in particular [@buchanan2007; @riede2019; @eerkens2005; @eerkens2007]. However, applying the abstract, formal models of cultural evolutionary theory to real-world archaeological data is not a straightforward process [@derex2020] and cultural evolutionary theory has itself continued to evolve. It is thus important to review potential points of confusion and/or refinement to this theoretical bedrock of contemporary evolutionary archaeology, including the underlying "culture as information" paradigm that cultural evolutionary theory inherited from its population genetics origins.

## Culture as Information

Evolutionary archaeology [@eerkens2007] follows cultural evolutionary theory (CET) in conceptualizing culture as information held in the minds of individuals. As phrased by Richerson and Boyd [-@richerson2005: 5]: "Culture is information capable of affecting individuals' behaviors that they acquire from other members of their species through teaching, imitation, and other forms of social transmission." This conception echoes the "genes as information" [@maynardsmith2000] paradigm that characterized the mid-century Modern Synthesis (MS) of evolutionary biology and which itself reflected the contemporaneous ascendance of computer science and information theory. In cultural anthropology as well, this computational zeitgeist was expressed in symbolic approaches to culture as "an information-holding system with functions similar to that of cellular DNA" such that "the instructions needed for coping with the environment and performing specialized roles is provided by learned information, which is symbolically encoded and culturally transmitted" [@dandrade1984: 198]. However, such symbolic approaches soon fell out of favor and were replaced by more enactive and embodied conceptions of culture as something people actually *do* [@bourdieu1977], and which is reciprocally constituted and constrained by the reproduction of patterned practices by individuals [@giddens1976]. This approach has been especially popular among archaeologists interested in apprenticeship and the co-production of material, mental, and social structures more generally [@apel2001], but the informational conception of culture as content to be transmitted or copied has remained dominant in CET and evolutionary archaeology.

This is somewhat ironic, as CET has now become an important part of a so-called "Extended Evolutionary Synthesis" (EES) that explicitly questions the MS conception of biological evolution as the transmission and expression of genetic information [@laland2015]. Whereas the MS defines biological evolution as changes in the frequency of gene variants in a population, and CET correspondingly conceives cultural evolution as "changes within a population of the relative frequencies of the forms of a cultural trait" [@cavalli-sforza1981: 5], the EES contends that "phenotypes are not inherited, they are reconstructed in development" [@laland2015: 5]. This active reconstruction (literally, re-production) is itself a source of adaptive variation and thus breaks down the classic MS distinction between "proximate" (e.g., ontogenetic) factors that merely inflect the expression of inherited genetic information and "ultimate" (e.g., natural selection) causes explaining "how the information came to be there in the first place" [@szathmáry1995: 231]. This leads EES to emphasize a wider range of evolutionary causes (e.g., niche construction, developmental processes, non-genetic inheritance) beyond mutation, selection, drift, and gene flow. Applied to culture, such logic calls for attention to diverse causes of culture reproduction and change beyond the social transmission of cultural information.

This is clearly exemplified by technology, which is arguably the most studies cultural domain for both CET and evolutionary archaeology. Causal mechanisms potentially contributing to technological stability and change extend beyond learning processes per se to include relative costs and benefits in particular behavioral systems and ecologies [@reek2018], social structure [@derex2020] and institutions [@roux2009], intrinsic features of [@stout2021] and/or interactions between [@kolodny2015] technologies, and potential coevolutionary relationships between these diverse factors [@kolodny2016]. Indeed, the CET literature is already replete with examples of material and causes of technological stability and change, including functional design demands, inflexible production processes and technological entrenchment, innovation cascades, market integration, environmental change, and more reviewed by Mesoudi et al [-@mesoudi2013: Table 11.2]. In the information transmission paradigm, such particular features are viewed as proximate mechanisms inflecting local rates and patterns of change rather than ultimate explanations for the origin of cultural diversity and adaptation. As in gene-centered approaches to biological evolution, the latter are expected to be expressed in purely terms of the population dynamics of information variation, transmission, and selection.

An alternative, EES inspired, approach would be to emphasize the causal power of such "proximate" mechanisms to actually drive evolutionary change. For example, there is some debate in the CET literature over whether technological innovation is usually blind and random (i.e., like genetic mutation) with optimization due to selective retention/copying (due to various biases discussed §1.1), or whether individual learning commonly acts to guide variation toward desired outcomes and allow for optimization even in the absence of selection [@mesoudi2021]. A largely neglected third possibility in this debate is that proximate material and social conditions can also guide variation and affect retention. A simple non-human example is the way in which the durability of artifacts and locations associated with some forms of primate tool use can facilitate the reproduction of tool behavior [@fragaszy2013]. In humans, ecology, ideology, and economics can affect the nature, frequency, and retention of innovations [@lew-levy2020] and particular technologies may be more or less evolvable due to the modularity vs. interdependence of component parts or procedures [@mesoudi2008].

As with the EES more broadly, this should not be construed as a repudiation of past work or even as presenting previously unrecognized mechanisms and/or empirical findings. In fact, one of the reasons the EES has been controversial is that its primary contribution is theoretical or even philosophical rather than empirical. The EES takes a stance on the nature and goals of evolutionary explanation whose relevance and appeal will depend in the questions and objectives of different research programs [@welch2017]. This is equally true with respect to the study of cultural evolution. Richerson and Boyd [-@richerson2005: 259] explicitly state that their definition of culture as information is a pragmatic one intended to promote productive research, rather than the only possible one. In this respect, it has clearly been successful. As with gene-centered approaches to biological evolution, the power of this informational approach stems from its relative simplicity, broad generalizability, and amenability to formal modeling. However, these broad strengths may be less well suited to explaining the precise causal-historical details of particular cases, especially when variables employed in formal models are difficult to relate to empirical measures of real-world data [@derex2020]. This parallels the case with the EES, which may be most relevant and helpful to researchers interested in detailed explanations of particular evolutionary histories [@welch2017]. Such a focus is more typically of evolutionary archaeology than it is of CET in general, but this has seldom been reflected in the theory and practice of the field.

For example, EES themes of developmental reconstruction and reciprocal organism-environment causation bear a conceptual similarity to the enactive and embodied approaches in cultural anthropology. However, the social theory of Bourdieu [-@bourdieu1977] and others has not generally been seen as amenable to practical application in evolutionary archaeology. One notable exception is Ingold's [@ingold1993: 158] concept of a "taskscape", as "an array of related activities" carrying forward social life that is inextricably bound with the landscape. Building on this concept, Tostevin [@tostevin2012: 85] coined the term taskscape visibility to refer to "the relationship between where, when, and with whom a cultural trait, such as a flintknapping behavior, is performed and the possible cultural transmission modes available for promulgating the trait into the next generation". This concept is then combined with social intimacy to predict certain aspects of lithic technology, mainly blank production, can only be visible and thus learned within socially intimate people like those living in the same camp. On the contrary, tool kit morphology is visible to more socially distant people such as two hunter-gatherers shortly meeting each other when their foraging landscape is overlapping. This approach adds a concrete technological and ecological particularism to the more abstracted investigation of population size and structure effects that is well developed in CET [@derex2020], but is correspondingly difficult to generalize and has not been widely adopted.

Another potential theoretical resource for evolutionary archaeology is the Cultural Attraction Theory (CAT) developed by Sperber [-@sperber1996] and colleagues [@scottphillips2018]. Again evoking EES themes, the core premise of CAT is that cultural traits are not straightforwardly transmitted or copied between individuals but must be actively reproduced. The particular processes and contexts of reproduction may then act as "factors of attraction" biasing the outcome in a particular direction ("convergent transformation") and resulting in either stabilization or directional change. Such convergent transformation would include the guided variation (trial and error learning) of Boyd and Richerson [-@boyd1985] but is a more inclusive concept that need not involve psychological factors affecting individual learning or lead to goal-directed enhancement [@acerbi2021]. Critically, CAT explicitly includes ecological (physical and social context) as well as psychological factors of attraction and theorizes culture change and stability as products of complex causal chains rather than biased information transmission [@scottphillips2018]. As such it would seem to be well suited to accommodate evolutionary archaeology interest in topics such as the way that specific artifact production techniques [@schillinger2014], perceptual-motor constraints [@pargeter2020], social contexts [@roux2009], and ecological interactions [@garvey2018] can affect cultural evolution. This potential has yet to be realized, however, as CAT work to date has tended to focus on communicative (e.g., songs, jokes, stories) culture and psychological factors of attraction rather than broader ecological causes [@scottphillips2018], and on explaining stability rather than change. Modeling has supported the in-principle potential of convergent transformation to supplement CET as an additional mechanism of cultural stabilization, but it remains an "abstract notion" [@acerbi2021: 3] yet to produce concrete archaeological predictions and applications comparable to CET [@riede2019].

Currently, then, there remains a disjunction between CET, with the broad explanatory scope and methodological advantages allowed by its simplifying focus on social transmission, and the more complex and particularistic array of causes and interactions relevant to understanding specific archaeological cases of culture change or stability [@garvey2018]. Bridging this gap with a more extended synthesis of cultural and evolutionary theory will be a major undertaking and an important priority for future work in evolutionary archaeology. In the remaining sections of this review, we consider current confusions and controversies arising from this theoretical disjunction and provide modest suggestions toward resolving them. These issues are perhaps most salient in debates over the evolutionary origins of human culture.

# The origins of human culture

## Requirements for CCE

## What is cumulative evolution?

# Identifying cultural reproduction at the intra-site level

# Identifying cultural reproduction at the inter-site level

# Future directions

# References
